spring.profiles.active=dev
# Nombre de la aplicación
spring.application.name=TechStorePro
server.port=8080

# Indicar a Spring que confíe en los encabezados del Proxy (Nginx/Docker)
server.forward-headers-strategy=native

# Configuración de Cloudinary (Reemplaza con tu URL real, pero sin la palabra "CLOUDINARY_URL=")
cloudinary.url=cloudinary://TU_API_KEY:TU_API_SECRET@TU_CLOUD_NAME
# Limites de subida de archivos (Multipart)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuración de Base de Datos (REEMPLAZAR CON DATOS LOCALES)
spring.datasource.url=jdbc:postgresql://localhost:5432/TU_BASE_DE_DATOS
spring.datasource.username=TU_USUARIO
spring.datasource.password=TU_CONTRASEÑA
spring.datasource.driver-class-name=org.postgresql.Driver

# Seguridad (JWT)
api.security.token.secret=${JWT_SECRET:TU_CLAVE_SECRETA_AQUI}
api.security.token.expiration=86400000

# Forzar a Spring a ejecutar scripts SQL de inicialización (por defecto se busca el archivo data.sql) / Cambiar never por always
spring.sql.init.mode=never